sudo: required
dist: trusty
language: node_js
node_js:
  - '6.4'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install

install:
- npm install

script:
- npm run test