sudo: required
dist: trusty
language: node_js
node_js:
  - '6.4'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install
- webdriver-manager update

script:
- tsc
- karma start karma.conf.js
- node_modules/lite-server/bin/lite-server &
- webdriver-manager start --standalone --passthru &
- node_modules/protractor/bin/protractor protractor.config.js --kill-others --success first --no-sandbox