sudo: required
dist: trusty
language: node_js
node_js:
  - '6.4'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start up

before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install
- tsc
- webdriver-manager update

script:
- karma start karma.conf.js
- node_modules/lite-server/bin/lite-server &
- sleep 10 # give lite-server some time to start uo
- webdriver-manager start &
- sleep 20 # give webdriver-manager some time to start uo
- node_modules/protractor/bin/protractor protractor.config.js --seleniumAddress http://localhost:4444/wd/hub --success first --no-sandbox